# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8a4fbc12dc37234ae706b8eae5b88b86390eb563eb66f4d63ca71af12ef385d512cb9da3bdc1cf514d42dd01add58f8b7a6f45b6b5334473198376135eef962

test:
  secret_key_base: dc546b6abd992def52aa1960281a5f9ed49ee132c8272d9ad870a6c69d67d15d362dba83ceb83f8c4eb9ede55cbbf9ee0dc72d9a1baaad023735d3d559c05345

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
